### ISSUE TITLE
Include CodeOptimist namespace

### ISSUE THREAD

**Issue by marr75** [CodeOptimist/rimworld-while-youre-up#8]
Seems you have a common set of "CodeOptimist" namespaced code that is required to compile this project (Transpiler, Helper, CodeInstructionComparer, etc.). It's trivial to go get that code from the assembly so I can compile locally/fork, but some structure and comments are lost and I end up with a local fork that will always have miscellaneous differences from the remote (because of the copy-pasted common classes).

Other options would be to factor it out into its own project and distribute the DLL or host the code in a repo.

This is the main reason I used the web interface to open that PR a few weeks ago - my local copy was messy from the classes I grabbed out of dnSpy.

**Comment by CodeOptimist** [comment]
I do indeed need to. I'm waaaay behind on publishing projects, I've got about 5 that are like 300% finished I should have published months ago (plus all the other incomplete projects). Trying to get it done though. Major somewhat emergency file server migration project last 2 weeks so even slower than usual.

**Comment by CodeOptimist** [comment]
This got me hella motivated though! https://www.youtube.com/watch?v=L1j93RnIxEo

**Comment by CodeOptimist** [comment]
YEARS LATER... all finished and pushed. This and https://github.com/CodeOptimist/rimworld-codeoptimist-library
