### ISSUE TITLE
Oct 24 3.2.1 Update

### ISSUE THREAD

**Issue by SpookyCongee** [CodeOptimist/rimworld-while-youre-up#9]
If possible, could you please update the repository to the current Steam version? If so, thanks!

**Comment by CodeOptimist** [comment]
Absolutely. This is right behind my "finish publishing my Open Broadcaster Script" project in the queue. Which I just finished and will be livestreaming the GitHub history cleanup and subsequent publishing of, probably tomorrow? https://twitch.tv/codeoptimist And _that_ project was right behind "update ahkUnwrapped", which I finished. ;)

I'll also work on publishing the CodeOptimist namespace with this. Also reorganizing the source a bit to be clear and adding comments.

**Comment by CodeOptimist** [comment]
This, v4.0.3, and the CodeOptimist library too, have finally been pushed to GitHub. It only took me a couple years. That's pretty good, right? Right? 🥹
